CREATE  PROCEDURE [dbo].[ALP_stpSISiteInsert]
(
	-- Updated for TRAV11 by Josh Gillespie on 04/26/2013
	--MAH 05/02/2017 - increased size of the ModifiedBy parameter, from 16 to 50 
	@SiteName VARCHAR(80) = NULL,
	@AlpFirstName VARCHAR(30) = NULL,
	@AlpDear VARCHAR(50) = NULL,
	@Status VARCHAR(10) = NULL,
	@Attn VARCHAR(30) = NULL,
	@Addr1 VARCHAR(40) = NULL,
	@Addr2  VARCHAR(60) = NULL,
	@City VARCHAR(30) = NULL,
	@Region VARCHAR(50) = NULL,
	@Country VARCHAR(6) = NULL,
	@PostalCode VARCHAR(10) = NULL,
	@IntlPrefix VARCHAR(6) = NULL,
	@Phone VARCHAR(15) = NULL,
	@Fax VARCHAR(15) = NULL,
	@Email TEXT = NULL,
	@CrossStreet VARCHAR(255) = NULL,
	@MapId VARCHAR(10) = NULL,
	@Directions TEXT = NULL,
	@SubDivId INT = NULL,
	@Block VARCHAR(255) = NULL,
	@SiteMemo TEXT = NULL,
	@SalesRepId1 VARCHAR(3) = NULL,
	@Rep1PctInvc NUMERIC(20,10) = NULL,
	@SalesRepId2 VARCHAR(3) = NULL,
	@Rep2PctInvc NUMERIC(20,10) = NULL,
	@TermsCode VARCHAR(6),
	@DistCode VARCHAR(6),
	@TaxLocId VARCHAR(10),
	@Taxable BIT = NULL,
	@CreditHoldYn BIT = NULL,
	@BranchId INT = NULL,
	@MarketId INT = NULL,
	@LeadSourceId INT = NULL,
	@ReferBy VARCHAR(255) = NULL,
	@ReferralFee NUMERIC(20,10) = NULL,
	@PromoId INT = NULL,
	@Structure TINYINT = NULL,
	@Basement TINYINT = NULL,
	@Attic TINYINT = NULL,
	@SqFt VARCHAR(50) = NULL,
	@InitialContactDate SMALLDATETIME = NULL,
	@PrefApptDate SMALLDATETIME = NULL,
	@PrefApptTime SMALLDATETIME = NULL,
	@DeadProspectYn BIT = NULL,
	@FinSourceId INT = NULL,
	@FinanceDate SMALLDATETIME = NULL,
	@FinanceEnds SMALLDATETIME = NULL,
	@Contact VARCHAR(255) = NULL,
	@County VARCHAR(50) = NULL,
	@OldSiteId VARCHAR(50) = NULL,
	@OldBillId VARCHAR(50) = NULL,
	@CreateDate SMALLDATETIME = NULL,
	@LastUpdateDate SMALLDATETIME = NULL,
	@UploadDate SMALLDATETIME = NULL,
	@BundledYn BIT = NULL,
	@RecurTaxLocId VARCHAR(10) = NULL,
	@DealerSiteYn BIT = NULL,
	@WDBTemplateYn BIT = NULL,
	@TaxExemptId VARCHAR(20) = NULL,
	@ModifiedBy VARCHAR(50) = NULL,
	@ModifiedDate DATETIME = NULL,
	@DisplayRmrInvoiceLineItemByMonth BIT = NULL,
	@SiteId INT OUTPUT
)
AS
BEGIN	
	INSERT INTO ALP_tblArAlpSite
		([SiteName],
		[AlpFirstName],
		[AlpDear],
		[Status],
		[Attn],
		[Addr1],
		[Addr2],
		[City],
		[Region],
		[Country],
		[PostalCode],
		[IntlPrefix],
		[Phone],
		[Fax],
		[Email],
		[CrossStreet],
		[MapId],
		[Directions],
		[SubDivID],
		[Block],
		[SiteMemo],
		[SalesRepId1],
		[Rep1PctInvc],
		[SalesRepId2],
		[Rep2PctInvc],
		[TermsCode],
		[DistCode],
		[TaxLocId],
		[Taxable],
		[CreditHoldYn],
		[BranchId],
		[MarketId],
		[LeadSourceId],
		[ReferBy],
		[Referral Fee],
		[PromoId],
		[Structure],
		[Basement],
		[Attic],
		[SqFt],
		[InitialContactDate],
		[PrefApptDate],
		[PrefApptTime],
		[DeadProspectYN],
		[FinSourceId],
		[FinanceDate],
		[FinanceEnds],
		[Contact],
		[County],
		[OldSiteId],
		[OldBillId],
		[CreateDate],
		[LastUpdateDate],
		[UploadDate],
		[BundledYn],
		[RecurTaxLocId],
		[DealerSiteYn],
		[WDBTemplateYn],
		[TaxExemptId],
		[ModifiedBy],
		[ModifiedDate],
		[DisplayRmrInvoiceLineItemByMonth])
	VALUES
		(@SiteName,@AlpFirstName ,@AlpDear , @Status , @Attn ,@Addr1 ,@Addr2, @City, @Region, @Country, @PostalCode, @IntlPrefix,
		 @Phone, @Fax, @Email, @CrossStreet, @MapId, @Directions, @SubDivId, @Block, @SiteMemo, @SalesRepId1, @Rep1PctInvc,
		 @SalesRepId2 ,	@Rep2PctInvc , @TermsCode , @DistCode ,	@TaxLocId, @Taxable, @CreditHoldYn , @BranchId,	@MarketId,
		 @LeadSourceId,	@ReferBy,@ReferralFee, @PromoId, @Structure, @Basement, @Attic, @SqFt, @InitialContactDate, @PrefApptDate,
		 @PrefApptTime, @DeadProspectYn,@FinSourceId, @FinanceDate, @FinanceEnds, @Contact, @County, @OldSiteId, @OldBillId,
		 @CreateDate, @LastUpdateDate, @UploadDate, @BundledYn,	@RecurTaxLocId, @DealerSiteYn, @WDBTemplateYn, @TaxExemptId, @ModifiedBy, @ModifiedDate, @DisplayRmrInvoiceLineItemByMonth)
		 
	SET @SiteId = (SELECT @@identity)
END