    
CREATE PROCEDURE [dbo].[ALP_stpSISiteRecJobUpdate]    
(    --The contact param length modified by ravi on 04.28.2014 (Earlier its 25 char not it has been changed to 60 char)  
 --MAH 05/02/2017 - increased size of the ModifiedBy parameter, from 16 to 50  
 @RecJobEntryId INT,    
 @CreateDate DATETIME = NULL,    
 @CustId VARCHAR(10) = NULL,    
 @SiteId INT = NULL,    
 @RecBillEntryId INT = NULL,    
 @RecSvcId INT = NULL,    
 @SysId INT = NULL,    
 @ContractId INT = NULL,    
 @CustPoNum VARCHAR(25) = NULL,    
 @JobCycleId INT = NULL,    
 @LastCycleStartDate DATETIME = NULL,    
 @NextCycleStartDate DATETIME = NULL,    
 @ExpirationDate DATETIME = NULL,    
 @LastDateCreated DATETIME = NULL,    
 --@Contact VARCHAR(25) = NULL,   
 @Contact VARCHAR(60) = NULL,    --The contact param length modified by ravi on 04.28.2014  
 @ContactPhone VARCHAR(15) = NULL,    
 @WorkDesc TEXT = NULL,    
 @WorkCodeId INT = NULL,    
 @RepPlanId INT = NULL,    
 @PriceId VARCHAR(15) = NULL,    
 @BranchId INT = NULL,    
 @DeptId INT = NULL,    
 @DivId INT = NULL,    
 @SkillId INT = NULL,    
 @PrefTechId INT = NULL,    
 @EstHrs FLOAT = NULL,    
 @PrefTime VARCHAR(50) = NULL,    
 @OtherComments TEXT = NULL,    
 @SalesRepId VARCHAR(3) = NULL,    
 @ModifiedBy VARCHAR(50) = NULL,    
 @ModifiedDate DATETIME = NULL,    
 @PhoneExt varchar(10)=null    
)    
AS    
BEGIN    
 UPDATE [srj]    
 SET [srj].[CreateDate] = @CreateDate,    
  [srj].[CustId] = @CustId,    
  [srj].[SiteId] = @SiteId,    
  [srj].[RecBillEntryId] = @RecBillEntryId,    
  [srj].[RecSvcId] = @RecSvcId,    
  [srj].[SysId] = @SysId,    
  [srj].[ContractId] = @ContractId,    
  [srj].[CustPoNum] = @CustPoNum,    
  [srj].[JobCycleId] = @JobCycleId,    
  [srj].[LastCycleStartDate] = @LastCycleStartDate,    
  [srj].[NextCycleStartDate] = @NextCycleStartDate,    
  [srj].[ExpirationDate] = @ExpirationDate,    
  [srj].[LastDateCreated] = @LastDateCreated,    
  [srj].[Contact] = @Contact,    
  [srj].[ContactPhone] = @ContactPhone,    
  [srj].[WorkDesc] = @WorkDesc,    
  [srj].[WorkCodeId] = @WorkCodeId,    
  [srj].[RepPlanId] = @RepPlanId,    
  [srj].[PriceId] = @PriceId,    
  [srj].[BranchId] = @BranchId,    
  [srj].[DeptId] = @DeptId,    
  [srj].[DivId] = @DivId,    
  [srj].[SkillId] = @SkillId,    
  [srj].[PrefTechId] = @PrefTechId,    
  [srj].[EstHrs] = @EstHrs,    
  [srj].[PrefTime] = @PrefTime,    
  [srj].[OtherComments] = @OtherComments,    
  [srj].[SalesRepId] = @SalesRepId,    
  [srj].[ModifiedBy] = @ModifiedBy,    
  [srj].[ModifiedDate] = @ModifiedDate,    
  [srj].[PhoneExt] = @PhoneExt    
 FROM [dbo].[ALP_tblArAlpSiteRecJob] AS [srj]    
 WHERE [srj].[RecJobEntryId] = @RecJobEntryId    
END