CREATE PROCEDURE [dbo].[ALP_stpSISiteRecBillServUpdate]
(
	-- Updated for TRAV11 by Josh Gillespie on 04/26/2013
	--MAH 05/02/2017 - increased size of the ModifiedBy parameter, from 16 to 50 
	@RecBillServId int,
	@RecBillId int = null,
	@Status  varchar(10) = null,
	@ServiceId varchar(24) = null,
	@Desc varchar(35) = null,
	@LocId varchar(10) = null,
	@ActivePrice decimal(20,10) = null,
	@ActiveCycleId int = null,
	@ActiveCost decimal(20,10) = null,
	@ActiveRMR decimal(20,10) = null,
	@AcctCode varchar(2) = null,
	@GLAcctSales varchar(40) = null,
	@GLAcctCOGS varchar(40) = null,
	@GLAcctInv varchar(40) = null,
	@DfltPrice decimal(20, 10) = null,
	@DfltCost decimal(20, 10) = null,
	@ServiceType smallint = null,
	@SysId int = null,
	@ExtRepPlanId int = null,
	@ContractId int = null,
	@InitialTerm smallint = null,
	@RenTerm smallint = null,
	@ServiceStartDate datetime = null,
	@BilledThruDate datetime = null,
	@FinalBillDate datetime = null,
	@AllowGlobalPriceChangeYn bit = null,
	@MinMths smallint = null,
	@NoChangePriorTo datetime = null,
	@AutoRenYn bit = null,
	@NotifyYn bit = null,
	@CanReasonId int = null,
	@CanComments text = null,
	@CanReportDate datetime = null,
	@CanServEndDate datetime = null,
	@CanCustId varchar(10) = null,
	@CanCustName varchar(30) = null,
	@CanSiteName varchar(80) = null,
	@CanCustFirstName varchar(30) = null,
	@CanSiteFirstName varchar(30) = null,
	@Processed bit = null,
	@ModifiedBy VARCHAR(50) = NULL,
	@ModifiedDate DATETIME = NULL
)
AS
BEGIN
	UPDATE [rbs]
	SET	[rbs].[RecBillId] = @RecBillId,
		[rbs].[Status]  = @Status ,
		[rbs].[ServiceID] = @ServiceId,
		[rbs].[Desc] = @Desc,
		[rbs].[LocID] = @LocId,
		[rbs].[ActivePrice] = @ActivePrice,
		[rbs].[ActiveCycleId] = @ActiveCycleId,
		[rbs].[ActiveCost] = @ActiveCost,
		[rbs].[ActiveRMR] = @ActiveRMR,
		[rbs].[AcctCode] = @AcctCode,
		[rbs].[GLAcctSales] = @GLAcctSales,
		[rbs].[GLAcctCOGS] = @GLAcctCOGS,
		[rbs].[GLAcctInv] = @GLAcctInv,
		[rbs].[DfltPrice] = @DfltPrice,
		[rbs].[DfltCost] = @DfltCost,
		[rbs].[ServiceType] = @ServiceType,
		[rbs].[SysId] = @SysId,
		[rbs].[ExtRepPlanId] = @ExtRepPlanId,
		[rbs].[ContractId] = @ContractId,
		[rbs].[InitialTerm] = @InitialTerm,
		[rbs].[RenTerm] = @RenTerm,
		[rbs].[ServiceStartDate] = @ServiceStartDate,
		[rbs].[BilledThruDate] = @BilledThruDate,
		[rbs].[FinalBillDate] = @FinalBillDate,
		[rbs].[AllowGlobalPriceChangeYN] = @AllowGlobalPriceChangeYn,
		[rbs].[MinMths] = @MinMths,
		[rbs].[NoChangePriorTo] = @NoChangePriorTo,
		[rbs].[AutoRenYN] = @AutoRenYn,
		[rbs].[NotifyYN] = @NotifyYn,
		[rbs].[CanReasonId] = @CanReasonId,
		[rbs].[CanComments] = @CanComments,
		[rbs].[CanReportDate] = @CanReportDate,
		[rbs].[CanServEndDate] = @CanServEndDate,
		[rbs].[CanCustId] = @CanCustId,
		[rbs].[CanCustName] = @CanCustName,
		[rbs].[CanSiteName] = @CanSiteName,
		[rbs].[CanCustFirstName] = @CanCustFirstName,
		[rbs].[CanSiteFirstName] = @CanSiteFirstName,
		[rbs].[Processed] = @Processed,
		[rbs].[ModifiedBy] = @ModifiedBy,
		[rbs].[ModifiedDate] = @ModifiedDate
	FROM [dbo].[ALP_tblArAlpSiteRecBillServ] AS [rbs]
	WHERE	[rbs].[RecBillServId] = @RecBillServId
END