CREATE TABLE [dbo].[ALP_tblArAlpReplaceCompletedSiteSysItem] (
    [SysItemId]        INT              NOT NULL,
    [SysId]            INT              NULL,
    [ItemId]           VARCHAR (24)     NULL,
    [Desc]             VARCHAR (255)    NULL,
    [LocId]            VARCHAR (10)     NULL,
    [PanelYN]          BIT              CONSTRAINT [DF_ALP_tblArAlpReplaceCompletedSiteSysItem_PanelYN] DEFAULT ((0)) NOT NULL,
    [SerNum]           VARCHAR (35)     NULL,
    [EquipLoc]         VARCHAR (30)     NULL,
    [Qty]              FLOAT (53)       NULL,
    [UnitCost]         NUMERIC (20, 10) NULL,
    [WarrPlanId]       INT              NULL,
    [WarrTerm]         SMALLINT         NULL,
    [WarrStarts]       DATETIME         NULL,
    [WarrExpires]      DATETIME         NULL,
    [Comments]         TEXT             NULL,
    [RemoveYN]         BIT              CONSTRAINT [DF_ALP_tblArAlpReplaceCompletedSiteSysItem_RemoveYN] DEFAULT ((0)) NOT NULL,
    [Zone]             VARCHAR (5)      NULL,
    [TicketId]         INT              NOT NULL,
    [WorkOrderId]      INT              NULL,
    [RepPlanId]        INT              NULL,
    [LeaseYN]          BIT              CONSTRAINT [DF_ALP_tblArAlpReplaceCompletedSiteSysItem_LeaseYN] DEFAULT ((0)) NOT NULL,
    [ts]               ROWVERSION       NULL,
    [ModifiedBy]       VARCHAR (50)     NULL,
    [ModifiedDate]     DATETIME         NULL,
    [UsedByOtherTktYN] INT              CONSTRAINT [DF_ALP_tblArAlpReplaceCompletedSiteSysItem_UsedByOtherTktYN] DEFAULT ((0)) NULL,
    [TicketItemId]     INT              NOT NULL,
    CONSTRAINT [PK_tblArAlpReplaceCompletedSiteSysItem] PRIMARY KEY CLUSTERED ([SysItemId] ASC, [TicketId] ASC)
);

