CREATE TABLE [dbo].[ALP_tmpArAlpSiteRecJob] (
    [RecJobEntryId]      INT          NOT NULL,
    [CreateDate]         DATETIME     NULL,
    [CustId]             VARCHAR (10) NULL,
    [SiteId]             INT          NULL,
    [RecBillEntryId]     INT          NULL,
    [RecSvcId]           INT          NULL,
    [SysId]              INT          NULL,
    [ContractId]         INT          NULL,
    [CustPoNum]          VARCHAR (25) NULL,
    [JobCycleId]         INT          NULL,
    [LastCycleStartDate] DATETIME     NULL,
    [NextCycleStartDate] DATETIME     NULL,
    [ExpirationDate]     DATETIME     NULL,
    [LastDateCreated]    DATETIME     NULL,
    [Contact]            VARCHAR (60) NULL,
    [ContactPhone]       VARCHAR (15) NULL,
    [WorkDesc]           TEXT         NULL,
    [WorkCodeId]         INT          NULL,
    [RepPlanId]          INT          NULL,
    [PriceId]            VARCHAR (15) NULL,
    [BranchId]           INT          NULL,
    [DeptId]             INT          NULL,
    [DivId]              INT          NULL,
    [SkillId]            INT          NULL,
    [PrefTechId]         INT          NULL,
    [EstHrs]             FLOAT (53)   NULL,
    [PrefTime]           VARCHAR (50) NULL,
    [OtherComments]      TEXT         NULL,
    [SalesRepId]         VARCHAR (3)  NULL,
    [ModifiedBy]         VARCHAR (50) NULL,
    [ModifiedDate]       DATETIME     NULL,
    [PhoneExt]           VARCHAR (10) NULL,
    [UserId]             VARCHAR (50) NULL
);

