CREATE TABLE [dbo].[ALP_tblArCust] (
    [AlpCustId]          [dbo].[pCustID] NOT NULL,
    [AlpAllowCharge]     BIT             NULL,
    [AlpFirstName]       VARCHAR (30)    NULL,
    [AlpDear]            VARCHAR (50)    NULL,
    [AlpJmCustLevel]     VARCHAR (10)    NULL,
    [AlpListServices]    BIT             CONSTRAINT [DF_ALP_tblArCust_AlpListServices] DEFAULT ((1)) NULL,
    [AlpInactive]        BIT             NULL,
    [AlpComment]         TEXT            NULL,
    [AlpCreditHoldDays]  SMALLINT        NULL,
    [AlpCommYn]          BIT             NULL,
    [AlpLastName]        VARCHAR (30)    NULL,
    [AlpTaxId]           VARCHAR (11)    NULL,
    [AlpBillCycleDay]    SMALLINT        NULL,
    [AlpAchAcctType]     VARCHAR (50)    NULL,
    [AlpAchAba]          VARCHAR (9)     NULL,
    [AlpAchAcctNo]       VARCHAR (50)    NULL,
    [AlpCreditBureau]    VARCHAR (50)    NULL,
    [AlpCreditScore]     SMALLINT        NULL,
    [AlpCreateDate]      DATETIME        NULL,
    [AlpLastUpdateDate]  DATETIME        NULL,
    [AlpUploadDate]      DATETIME        NULL,
    [AlpOldCustId]       VARCHAR (10)    NULL,
    [AlpDealerYn]        BIT             NULL,
    [AlpEmbContractType] VARCHAR (3)     NULL,
    [AlpPoRequiredYn]    BIT             NULL,
    [Alpts]              ROWVERSION      NULL,
    CONSTRAINT [PK_ALP_tblArCust] PRIMARY KEY CLUSTERED ([AlpCustId] ASC)
);

