CREATE TABLE [dbo].[ALP_tblQMR] (
    [ID]    INT           NOT NULL,
    [RDate] SMALLDATETIME NOT NULL,
    [RId]   VARCHAR (20)  CONSTRAINT [DF_tblQMR_RId] DEFAULT ('') NOT NULL,
    CONSTRAINT [PK_ALP_tblQMR] PRIMARY KEY CLUSTERED ([ID] ASC)
);

