CREATE TABLE [dbo].[ALP_tmpJmRecurJob] (
    [RecJobEntryId]      INT           NOT NULL,
    [CreateDate]         DATETIME      NULL,
    [CustId]             VARCHAR (10)  NULL,
    [SiteId]             INT           NULL,
    [RecBillEntryId]     INT           NULL,
    [RecSvcId]           INT           NULL,
    [SysId]              INT           NULL,
    [ContractId]         INT           NULL,
    [CustPoNum]          VARCHAR (25)  NULL,
    [JobCycleId]         INT           NULL,
    [LastCycleStartDate] DATETIME      NULL,
    [NextCycleStartDate] DATETIME      NULL,
    [ExpirationDate]     DATETIME      NULL,
    [LastDateCreated]    DATETIME      NULL,
    [Contact]            VARCHAR (60)  NULL,
    [ContactPhone]       VARCHAR (15)  NULL,
    [WorkDesc]           TEXT          NULL,
    [WorkCodeId]         INT           NULL,
    [RepPlanId]          INT           NULL,
    [PriceId]            VARCHAR (15)  NULL,
    [BranchId]           INT           NULL,
    [DeptId]             INT           NULL,
    [DivId]              INT           NULL,
    [SkillId]            INT           NULL,
    [PrefTechId]         INT           NULL,
    [EstHrs]             FLOAT (53)    NULL,
    [PrefTime]           VARCHAR (50)  NULL,
    [OtherComments]      TEXT          NULL,
    [SalesRepId]         VARCHAR (3)   NULL,
    [SiteName]           VARCHAR (80)  NULL,
    [Cycle]              VARCHAR (10)  NULL,
    [SysDesc]            VARCHAR (255) NULL,
    [WorkCode]           VARCHAR (10)  NULL,
    [ServiceID]          VARCHAR (24)  NULL,
    [InstallDate]        DATETIME      NULL,
    [Status]             VARCHAR (10)  NULL,
    [Units]              NUMERIC (18)  NULL,
    [ClassId]            VARCHAR (6)   NULL,
    [UserId]             VARCHAR (50)  NULL,
    CONSTRAINT [PK_ALP_tmpJmRecurJob] PRIMARY KEY CLUSTERED ([RecJobEntryId] ASC)
);

