CREATE TABLE [dbo].[tblArTransDetail] (
    [TransID]               [dbo].[pTransID]     NOT NULL,
    [EntryNum]              INT                  NOT NULL,
    [ItemJob]               TINYINT              CONSTRAINT [DF__tblArTran__ItemJ__34F7BB0D] DEFAULT (0) NULL,
    [WhseId]                [dbo].[pLocID]       NULL,
    [PartId]                [dbo].[pItemID]      NULL,
    [JobId]                 VARCHAR (10)         NULL,
    [PhaseId]               VARCHAR (10)         NULL,
    [JobCompleteYN]         BIT                  CONSTRAINT [DF__tblArTran__JobCo__35EBDF46] DEFAULT (0) NULL,
    [Desc]                  [dbo].[pDescription] NULL,
    [LottedYn]              BIT                  CONSTRAINT [DF__tblArTran__Lotte__36E0037F] DEFAULT (0) NULL,
    [PartType]              TINYINT              CONSTRAINT [DF__tblArTran__PartT__37D427B8] DEFAULT (0) NULL,
    [AddnlDesc]             TEXT                 NULL,
    [CatId]                 VARCHAR (2)          NULL,
    [TaxClass]              TINYINT              CONSTRAINT [DF__tblArTran__TaxCl__38C84BF1] DEFAULT (0) NULL,
    [AcctCode]              [dbo].[pGLAcctCode]  NULL,
    [GLAcctSales]           [dbo].[pGlAcct]      NULL,
    [GLAcctCOGS]            [dbo].[pGlAcct]      NULL,
    [GLAcctInv]             [dbo].[pGlAcct]      NULL,
    [QtyOrdSell]            [dbo].[pDec]         CONSTRAINT [DF_tblArTransDetail_QtyOrdSell] DEFAULT (0) NULL,
    [UnitsSell]             [dbo].[pUom]         NULL,
    [UnitsBase]             [dbo].[pUom]         NULL,
    [QtyShipBase]           [dbo].[pDec]         CONSTRAINT [DF_tblArTransDetail_QtyShipBase] DEFAULT (0) NULL,
    [QtyShipSell]           [dbo].[pDec]         CONSTRAINT [DF_tblArTransDetail_QtyShipSell] DEFAULT (0) NULL,
    [QtyBackordSell]        [dbo].[pDec]         CONSTRAINT [DF_tblArTransDetail_QtyBackordSell] DEFAULT (0) NULL,
    [PriceCode]             VARCHAR (10)         NULL,
    [UnitPriceSell]         [dbo].[pDec]         CONSTRAINT [DF_tblArTransDetail_UnitPriceSell] DEFAULT (0) NULL,
    [UnitCostSell]          [dbo].[pDec]         CONSTRAINT [DF_tblArTransDetail_UnitCostSell] DEFAULT (0) NULL,
    [UnitPriceSellFgn]      [dbo].[pDec]         CONSTRAINT [DF_tblArTransDetail_UnitPriceSellFgn] DEFAULT (0) NULL,
    [UnitCostSellFgn]       [dbo].[pDec]         CONSTRAINT [DF_tblArTransDetail_UnitCostSellFgn] DEFAULT (0) NULL,
    [HistSeqNum]            INT                  CONSTRAINT [DF__tblArTran__HistS__415D91F2] DEFAULT (0) NULL,
    [ExtCost]               [dbo].[pDec]         CONSTRAINT [DF_tblArTransDetail_ExtCost] DEFAULT (0) NULL,
    [ExtFinalInc]           [dbo].[pDec]         CONSTRAINT [DF_tblArTransDetail_ExtFinalInc] DEFAULT (0) NULL,
    [ExtOrigInc]            [dbo].[pDec]         CONSTRAINT [DF_tblArTransDetail_ExtOrigInc] DEFAULT (0) NULL,
    [TransHistId]           VARCHAR (10)         NULL,
    [TaskId]                VARCHAR (10)         NULL,
    [PhaseName]             VARCHAR (30)         NULL,
    [ProjName]              VARCHAR (30)         NULL,
    [ExtFinalIncFgn]        [dbo].[pDec]         CONSTRAINT [DF_tblArTransDetail_ExtFinalIncFgn] DEFAULT (0) NULL,
    [TaskName]              VARCHAR (30)         NULL,
    [QtySeqNum]             INT                  CONSTRAINT [DF_tblArTransDetail_QtySeqNum] DEFAULT (0) NULL,
    [ts]                    ROWVERSION           NULL,
    [ReqShipDate]           DATETIME             NULL,
    [PriceExt]              [dbo].[pDec]         CONSTRAINT [DF_tblArTransDetail_PriceExt] DEFAULT ((0)) NULL,
    [PriceExtFgn]           [dbo].[pDec]         CONSTRAINT [DF_tblArTransDetail_PriceExtFgn] DEFAULT ((0)) NULL,
    [CostExtFgn]            [dbo].[pDec]         CONSTRAINT [DF_tblArTransDetail_CostExtFgn] DEFAULT ((0)) NULL,
    [CostExt]               [dbo].[pDec]         CONSTRAINT [DF_tblArTransDetail_CostExt] DEFAULT ((0)) NULL,
    [PriceAdjAmt]           [dbo].[pDec]         DEFAULT ((0)) NULL,
    [PriceAdjAmtFgn]        [dbo].[pDec]         DEFAULT ((0)) NULL,
    [PriceAdjPct]           [dbo].[pDec]         DEFAULT ((0)) NULL,
    [PriceAdjType]          TINYINT              DEFAULT ((0)) NULL,
    [Rep1CommRate]          [dbo].[pDec]         DEFAULT ((0)) NULL,
    [Rep1Id]                [dbo].[pSalesRep]    NULL,
    [Rep1Pct]               [dbo].[pDec]         DEFAULT ((0)) NULL,
    [Rep2CommRate]          [dbo].[pDec]         DEFAULT ((0)) NULL,
    [Rep2Id]                [dbo].[pSalesRep]    NULL,
    [Rep2Pct]               [dbo].[pDec]         DEFAULT ((0)) NULL,
    [UnitCommBasis]         [dbo].[pDec]         DEFAULT ((0)) NULL,
    [UnitCommBasisFgn]      [dbo].[pDec]         DEFAULT ((0)) NULL,
    [UnitPriceSellBasis]    [dbo].[pDec]         DEFAULT ((0)) NULL,
    [UnitPriceSellBasisFgn] [dbo].[pDec]         DEFAULT ((0)) NULL,
    [ZeroPrint]             BIT                  DEFAULT ((0)) NULL,
    [LineSeq]               INT                  NULL,
    [CF]                    XML                  NULL,
    [CustomerPartNumber]    [dbo].[pDescription] NULL,
    CONSTRAINT [PK_tblArTransDetail] PRIMARY KEY CLUSTERED ([TransID] ASC, [EntryNum] ASC)
);


GO
EXECUTE sp_addextendedproperty @name = N'Version', @value = '11.0.19137.3213', @level0type = N'SCHEMA', @level0name = N'dbo', @level1type = N'TABLE', @level1name = N'tblArTransDetail';


GO
EXECUTE sp_addextendedproperty @name = N'Comment', @value = 'Build 19137', @level0type = N'SCHEMA', @level0name = N'dbo', @level1type = N'TABLE', @level1name = N'tblArTransDetail';

