CREATE TABLE [dbo].[tblApVendor] (
    [VendorID]            [dbo].[pVendorID]  NOT NULL,
    [Name]                VARCHAR (30)       NULL,
    [Contact]             VARCHAR (30)       NULL,
    [Addr1]               VARCHAR (30)       NULL,
    [Addr2]               VARCHAR (60)       NULL,
    [City]                VARCHAR (30)       NULL,
    [Region]              VARCHAR (10)       NULL,
    [Country]             [dbo].[pCountry]   NOT NULL,
    [PostalCode]          VARCHAR (10)       NULL,
    [IntlPrefix]          VARCHAR (6)        NULL,
    [Phone]               VARCHAR (15)       NULL,
    [FAX]                 VARCHAR (15)       NULL,
    [OurAcctNum]          VARCHAR (25)       NULL,
    [PayToName]           VARCHAR (30)       NULL,
    [PayToAttention]      VARCHAR (30)       NULL,
    [PayToAddr1]          VARCHAR (30)       NULL,
    [PayToAddr2]          VARCHAR (60)       NULL,
    [PayToCity]           VARCHAR (30)       NULL,
    [PayToRegion]         VARCHAR (10)       NULL,
    [PayToCountry]        [dbo].[pCountry]   NULL,
    [PayToPostalCode]     VARCHAR (10)       NULL,
    [PayToIntlPrefix]     VARCHAR (6)        NULL,
    [PayToPhone]          VARCHAR (15)       NULL,
    [Ten99FormCode]       VARCHAR (1)        NOT NULL,
    [Ten99RecipientID]    VARCHAR (16)       NULL,
    [Ten99FieldIndicator] VARCHAR (1)        NULL,
    [Ten99ForeignAddrYN]  BIT                NULL,
    [SecondTINNotYN]      BIT                NULL,
    [GLAcct]              [dbo].[pGlAcct]    NULL,
    [PriorityCode]        VARCHAR (1)        NULL,
    [VendorHoldYN]        BIT                CONSTRAINT [DF__tblApVend__Vendo__74BD3A67] DEFAULT (0) NULL,
    [TempYN]              BIT                CONSTRAINT [DF__tblApVend__TempY__75B15EA0] DEFAULT (0) NULL,
    [VendorClass]         VARCHAR (6)        NULL,
    [TermsCode]           [dbo].[pTermsCode] NOT NULL,
    [DivisionCode]        VARCHAR (6)        NULL,
    [DistCode]            [dbo].[pDistCode]  NOT NULL,
    [TaxableYN]           BIT                CONSTRAINT [DF__tblApVend__Taxab__76A582D9] DEFAULT (1) NULL,
    [Memo]                TEXT               NULL,
    [CurrencyId]          [dbo].[pCurrency]  NOT NULL,
    [TaxGrpID]            [dbo].[pTaxLoc]    NOT NULL,
    [Email]               [dbo].[pEmail]     NULL,
    [Internet]            [dbo].[pWeb]       NULL,
    [LastPurchDate]       DATETIME           NULL,
    [LastPurchNum]        VARCHAR (15)       NULL,
    [LastPmtDate]         DATETIME           NULL,
    [LastCheckNum]        [dbo].[pCheckNum]  NULL,
    [LastPurchAmt]        [dbo].[pDec]       CONSTRAINT [DF_tblApVendor_LastPurchAmt] DEFAULT (0) NOT NULL,
    [LastPmtAmt]          [dbo].[pDec]       CONSTRAINT [DF_tblApVendor_LastPmtAmt] DEFAULT (0) NOT NULL,
    [GrossDue]            [dbo].[pDec]       CONSTRAINT [DF_tblApVendor_GrossDue] DEFAULT (0) NOT NULL,
    [Prepaid]             [dbo].[pDec]       CONSTRAINT [DF_tblApVendor_Prepaid] DEFAULT (0) NOT NULL,
    [LastPurchAmtFgn]     [dbo].[pDec]       CONSTRAINT [DF_tblApVendor_LastPurchAmtFgn] DEFAULT (0) NOT NULL,
    [LastPmtAmtFgn]       [dbo].[pDec]       CONSTRAINT [DF_tblApVendor_LastPmtAmtFgn] DEFAULT (0) NOT NULL,
    [GrossDueFgn]         [dbo].[pDec]       CONSTRAINT [DF_tblApVendor_GrossDueFgn] DEFAULT (0) NOT NULL,
    [PrepaidFgn]          [dbo].[pDec]       CONSTRAINT [DF_tblApVendor_PrepaidFgn] DEFAULT (0) NOT NULL,
    [ts]                  ROWVERSION         NULL,
    [DfltTransAllocId]    VARCHAR (10)       NULL,
    [ChkOpt]              TINYINT            DEFAULT ((0)) NOT NULL,
    [Status]              TINYINT            DEFAULT ((0)) NOT NULL,
    [DeliveryType]        TINYINT            DEFAULT ((0)) NULL,
    [BankAcctNum]         NVARCHAR (255)     NULL,
    [MaskValue]           VARCHAR (4)        NULL,
    [RoutingCode]         VARCHAR (9)        NULL,
    [DefaultPayBankId]    [dbo].[pBankID]    NULL,
    [CF]                  XML                NULL,
    [BankAccountType]     TINYINT            CONSTRAINT [DF_tblApVendor_BankAccountType] DEFAULT ((0)) NOT NULL,
    CONSTRAINT [PK__tblApVendor__1975C517] PRIMARY KEY CLUSTERED ([VendorID] ASC) WITH (FILLFACTOR = 80)
);


GO
EXECUTE sp_addextendedproperty @name = N'Version', @value = '11.0.19137.3213', @level0type = N'SCHEMA', @level0name = N'dbo', @level1type = N'TABLE', @level1name = N'tblApVendor';


GO
EXECUTE sp_addextendedproperty @name = N'Comment', @value = 'Build 19137', @level0type = N'SCHEMA', @level0name = N'dbo', @level1type = N'TABLE', @level1name = N'tblApVendor';

