CREATE TABLE [dbo].[tblPaPrepMagMed] (
    [Counter]           INT              IDENTITY (1, 1) NOT NULL,
    [EmployeeId]        [dbo].[pEmpID]   NULL,
    [LastName]          NVARCHAR (20)    NULL,
    [FirstName]         NVARCHAR (15)    NULL,
    [MiddleInit]        NVARCHAR (1)     NULL,
    [Suffix]            NVARCHAR (4)     NULL,
    [BoxB]              NVARCHAR (17)    NULL,
    [BoxC]              NVARCHAR (50)    NULL,
    [BoxC1]             NVARCHAR (70)    NULL,
    [BoxA]              NVARCHAR (255)   NULL,
    [BoxE]              NVARCHAR (70)    NULL,
    [AddressLine1]      NVARCHAR (30)    NULL,
    [AddressLine2]      NVARCHAR (60)    NULL,
    [BoxF1]             NVARCHAR (25)    NULL,
    [BoxF2]             NVARCHAR (23)    NULL,
    [BoxF3]             NVARCHAR (15)    NULL,
    [BoxF4]             NVARCHAR (4)     NULL,
    [Box15a]            BIT              CONSTRAINT [DF_tblPaPrepMagMed_Box15a] DEFAULT ((0)) NULL,
    [Box15b]            BIT              CONSTRAINT [DF_tblPaPrepMagMed_Box15b] DEFAULT ((0)) NULL,
    [Box15c]            BIT              CONSTRAINT [DF_tblPaPrepMagMed_Box15c] DEFAULT ((0)) NULL,
    [Box15f]            BIT              CONSTRAINT [DF_tblPaPrepMagMed_Box15f] DEFAULT ((0)) NULL,
    [chkThirdPartySP]   BIT              CONSTRAINT [DF_tblPaPrepMagMed_chkThirdPartySP] DEFAULT ((0)) NULL,
    [Box16a]            NVARCHAR (4)     NULL,
    [SumOfBox1]         [dbo].[pDec]     CONSTRAINT [DF_tblPaPrepMagMed_SumOfBox1] DEFAULT ((0)) NOT NULL,
    [SumOfBox2]         [dbo].[pDec]     CONSTRAINT [DF_tblPaPrepMagMed_SumOfBox2] DEFAULT ((0)) NOT NULL,
    [SumOfBox3]         [dbo].[pDec]     CONSTRAINT [DF_tblPaPrepMagMed_SumOfBox3] DEFAULT ((0)) NOT NULL,
    [SumOfBox4]         [dbo].[pDec]     CONSTRAINT [DF_tblPaPrepMagMed_SumOfBox4] DEFAULT ((0)) NOT NULL,
    [SumOfBox5]         [dbo].[pDec]     CONSTRAINT [DF_tblPaPrepMagMed_SumOfBox5] DEFAULT ((0)) NOT NULL,
    [SumOfBox6]         [dbo].[pDec]     CONSTRAINT [DF_tblPaPrepMagMed_SumOfBox6] DEFAULT ((0)) NOT NULL,
    [SumOfBox7]         [dbo].[pDec]     CONSTRAINT [DF_tblPaPrepMagMed_SumOfBox7] DEFAULT ((0)) NOT NULL,
    [SumOfBox8]         [dbo].[pDec]     CONSTRAINT [DF_tblPaPrepMagMed_SumOfBox8] DEFAULT ((0)) NOT NULL,
    [SumOfBox9]         [dbo].[pDec]     CONSTRAINT [DF_tblPaPrepMagMed_SumOfBox9] DEFAULT ((0)) NOT NULL,
    [SumOfBox10]        [dbo].[pDec]     CONSTRAINT [DF_tblPaPrepMagMed_SumOfBox10] DEFAULT ((0)) NOT NULL,
    [SumOfBox11]        [dbo].[pDec]     CONSTRAINT [DF_tblPaPrepMagMed_SumOfBox11] DEFAULT ((0)) NOT NULL,
    [SumOfBox12]        [dbo].[pDec]     CONSTRAINT [DF_tblPaPrepMagMed_SumOfBox12] DEFAULT ((0)) NOT NULL,
    [SumOfBox17]        [dbo].[pDec]     CONSTRAINT [DF_tblPaPrepMagMed_SumOfBox17] DEFAULT ((0)) NOT NULL,
    [SumOfBox18]        [dbo].[pDec]     CONSTRAINT [DF_tblPaPrepMagMed_SumOfBox18] DEFAULT ((0)) NOT NULL,
    [SumOfBox20]        [dbo].[pDec]     CONSTRAINT [DF_tblPaPrepMagMed_SumOfBox20] DEFAULT ((0)) NOT NULL,
    [SumOfBox21]        [dbo].[pDec]     CONSTRAINT [DF_tblPaPrepMagMed_SumOfBox21] DEFAULT ((0)) NOT NULL,
    [SUITotWages]       [dbo].[pDec]     CONSTRAINT [DF_tblPaPrepMagMed_SUITotWages] DEFAULT ((0)) NOT NULL,
    [SUITotTaxWages]    [dbo].[pDec]     CONSTRAINT [DF_tblPaPrepMagMed_SUITotTaxWages] DEFAULT ((0)) NOT NULL,
    [SumOfBox13Line1]   [dbo].[pDec]     CONSTRAINT [DF_tblPaPrepMagMed_SumOfBox13Line1] DEFAULT ((0)) NOT NULL,
    [SumOfBox13Line2]   [dbo].[pDec]     CONSTRAINT [DF_tblPaPrepMagMed_SumOfBox13Line2] DEFAULT ((0)) NOT NULL,
    [SumOfBox13Line3]   [dbo].[pDec]     CONSTRAINT [DF_tblPaPrepMagMed_SumOfBox13Line3] DEFAULT ((0)) NOT NULL,
    [SumOfBox14Line1]   [dbo].[pDec]     CONSTRAINT [DF_tblPaPrepMagMed_SumOfBox14Line1] DEFAULT ((0)) NOT NULL,
    [SumOfBox14Line2]   [dbo].[pDec]     CONSTRAINT [DF_tblPaPrepMagMed_SumOfBox14Line2] DEFAULT ((0)) NOT NULL,
    [SumOfBox14Line3]   [dbo].[pDec]     CONSTRAINT [DF_tblPaPrepMagMed_SumOfBox14Line3] DEFAULT ((0)) NOT NULL,
    [Box13LineDesc1]    NVARCHAR (40)    NULL,
    [Box13LineDesc2]    NVARCHAR (40)    NULL,
    [Box13LineDesc3]    NVARCHAR (40)    NULL,
    [DesigRothContrAA]  [dbo].[pDec]     CONSTRAINT [DF_tblPaPrepMagMed_DesigRothContrAA] DEFAULT ((0)) NOT NULL,
    [DesigRothContrBB]  [dbo].[pDec]     CONSTRAINT [DF_tblPaPrepMagMed_DesigRothContrBB] DEFAULT ((0)) NOT NULL,
    [DefCompD]          [dbo].[pDec]     CONSTRAINT [DF_tblPaPrepMagMed_DefCompD] DEFAULT ((0)) NOT NULL,
    [DefCompE]          [dbo].[pDec]     CONSTRAINT [DF_tblPaPrepMagMed_DefCompE] DEFAULT ((0)) NOT NULL,
    [DefCompF]          [dbo].[pDec]     CONSTRAINT [DF_tblPaPrepMagMed_DefCompF] DEFAULT ((0)) NOT NULL,
    [DefCompG]          [dbo].[pDec]     CONSTRAINT [DF_tblPaPrepMagMed_DefCompG] DEFAULT ((0)) NOT NULL,
    [DefCompH]          [dbo].[pDec]     CONSTRAINT [DF_tblPaPrepMagMed_DefCompH] DEFAULT ((0)) NOT NULL,
    [Military]          [dbo].[pDec]     CONSTRAINT [DF_tblPaPrepMagMed_Military] DEFAULT ((0)) NOT NULL,
    [NON457]            [dbo].[pDec]     CONSTRAINT [DF_tblPaPrepMagMed_NON457] DEFAULT ((0)) NOT NULL,
    [sec457]            [dbo].[pDec]     CONSTRAINT [DF_tblPaPrepMagMed_sec457] DEFAULT ((0)) NOT NULL,
    [GTLI]              [dbo].[pDec]     CONSTRAINT [DF_tblPaPrepMagMed_GTLI] DEFAULT ((0)) NOT NULL,
    [HSAW]              [dbo].[pDec]     CONSTRAINT [DF_tblPaPrepMagMed_HSAW] DEFAULT ((0)) NOT NULL,
    [NonTaxCmbPay]      [dbo].[pDec]     CONSTRAINT [DF_tblPaPrepMagMed_NonTaxCmbPay] DEFAULT ((0)) NOT NULL,
    [Def409ANonQDC]     [dbo].[pDec]     CONSTRAINT [DF_tblPaPrepMagMed_Def409ANonQDC] DEFAULT ((0)) NOT NULL,
    [Inc409ANonQDC]     [dbo].[pDec]     CONSTRAINT [DF_tblPaPrepMagMed_Inc409ANonQDC] DEFAULT ((0)) NOT NULL,
    [ContrUnder457b]    [dbo].[pDec]     CONSTRAINT [DF_tblPaPrepMagMed_ContrUnder457b] DEFAULT ((0)) NOT NULL,
    [EmplrCostSpsCovrg] [dbo].[pDec]     CONSTRAINT [DF_tblPaPrepMagMed_EmplrCostSpsCovrg] DEFAULT ((0)) NOT NULL,
    [OptionalCode]      NVARCHAR (2)     NULL,
    [ReportPeriod]      NVARCHAR (6)     NULL,
    [StartDate]         DATETIME         NULL,
    [TerminDate]        DATETIME         NULL,
    [OtherStateData]    NVARCHAR (10)    NULL,
    [Box16b]            NVARCHAR (20)    NULL,
    [TaxTypeCode]       NVARCHAR (1)     NULL,
    [StateCode]         INT              CONSTRAINT [DF_tblPaPrepMagMed_StateCode] DEFAULT ((0)) NOT NULL,
    [SupplData1]        NVARCHAR (75)    NULL,
    [SupplData2]        NVARCHAR (75)    NULL,
    [StateControlNo]    INT              NULL,
    [WeeksNo]           INT              CONSTRAINT [DF_tblPaPrepMagMed_WeeksNo] DEFAULT ((0)) NOT NULL,
    [StateRec]          BIT              CONSTRAINT [DF_tblPaPrepMagMed_StateRec] DEFAULT ((0)) NULL,
    [ExercNonStatOpt]   [dbo].[pDec]     CONSTRAINT [DF_tblPaPrepMagMed_ExercNonStatOpt] DEFAULT ((0)) NOT NULL,
    [UncollOASDIMed]    [dbo].[pDec]     CONSTRAINT [DF_tblPaPrepMagMed_UncollOASDIMed] DEFAULT ((0)) NOT NULL,
    [UncollMed]         [dbo].[pDec]     CONSTRAINT [DF_tblPaPrepMagMed_UncollMed] DEFAULT ((0)) NOT NULL,
    [UncollRRTA]        [dbo].[pDec]     CONSTRAINT [DF_tblPaPrepMagMed_UncollRRTA] DEFAULT ((0)) NOT NULL,
    [MedSavAccount]     [dbo].[pDec]     CONSTRAINT [DF_tblPaPrepMagMed_MedSavAccount] DEFAULT ((0)) NOT NULL,
    [SimpRetAccount]    [dbo].[pDec]     CONSTRAINT [DF_tblPaPrepMagMed_SimpRetAccount] DEFAULT ((0)) NOT NULL,
    [QualAdopExp]       [dbo].[pDec]     CONSTRAINT [DF_tblPaPrepMagMed_QualAdopExp] DEFAULT ((0)) NOT NULL,
    [SpouseSSN]         NVARCHAR (255)   NULL,
    [CivilStatus]       NVARCHAR (1)     NULL,
    [PRCommissions]     [dbo].[pDec]     CONSTRAINT [DF_tblPaPrepMagMed_PRCommissions] DEFAULT ((0)) NOT NULL,
    [PRAllowances]      [dbo].[pDec]     CONSTRAINT [DF_tblPaPrepMagMed_PRAllowances] DEFAULT ((0)) NOT NULL,
    [PRTipsSubjTax]     [dbo].[pDec]     CONSTRAINT [DF_tblPaPrepMagMed_PRTipsSubjTax] DEFAULT ((0)) NOT NULL,
    [PRRetirFund]       [dbo].[pDec]     CONSTRAINT [DF_tblPaPrepMagMed_PRRetirFund] DEFAULT ((0)) NOT NULL,
    [VirgIslTotWages]   [dbo].[pDec]     CONSTRAINT [DF_tblPaPrepMagMed_VirgIslTotWages] DEFAULT ((0)) NOT NULL,
    [VirgIslIncomeTax]  [dbo].[pDec]     CONSTRAINT [DF_tblPaPrepMagMed_VirgIslIncomeTax] DEFAULT ((0)) NOT NULL,
    [TaxEntityCode]     NVARCHAR (5)     NULL,
    [Territories]       BIT              CONSTRAINT [DF_tblPaPrepMagMed_Territories] DEFAULT ((0)) NULL,
    [chkForeign]        BIT              CONSTRAINT [DF_tblPaPrepMagMed_chkForeign] DEFAULT ((0)) NULL,
    [ts]                ROWVERSION       NULL,
    [QSEHRA]            [dbo].[pDecimal] CONSTRAINT [DF_tblPaPrepMagMed_QSEHRA] DEFAULT ((0)) NOT NULL,
    [GGQEG]             [dbo].[pDecimal] CONSTRAINT [DF_tblPaPrepMagMed_GGQEG] DEFAULT ((0)) NOT NULL,
    [HHADF]             [dbo].[pDecimal] CONSTRAINT [DF_tblPaPrepMagMed_HHADF] DEFAULT ((0)) NOT NULL,
    CONSTRAINT [PK_tblPaPrepMagMed] PRIMARY KEY CLUSTERED ([Counter] ASC)
);


GO
EXECUTE sp_addextendedproperty @name = N'Version', @value = '11.0.19137.3213', @level0type = N'SCHEMA', @level0name = N'dbo', @level1type = N'TABLE', @level1name = N'tblPaPrepMagMed';


GO
EXECUTE sp_addextendedproperty @name = N'Comment', @value = 'Build 19137', @level0type = N'SCHEMA', @level0name = N'dbo', @level1type = N'TABLE', @level1name = N'tblPaPrepMagMed';

