CREATE TABLE [dbo].[tblPoHistRequestHeader] (
    [PostRun]             [dbo].[pPostRun]   NOT NULL,
    [TransId]             [dbo].[pTransID]   NOT NULL,
    [BatchId]             [dbo].[pBatchID]   NOT NULL,
    [TransType]           SMALLINT           NULL,
    [LocId]               [dbo].[pLocID]     NULL,
    [VendorId]            [dbo].[pVendorID]  NULL,
    [Notes]               TEXT               NULL,
    [DistCode]            [dbo].[pDistCode]  NULL,
    [TermsCode]           [dbo].[pTermsCode] NULL,
    [TransDate]           DATETIME           NULL,
    [TaxGrpID]            [dbo].[pTaxLoc]    NULL,
    [TaxableYn]           BIT                DEFAULT ((1)) NULL,
    [PrintStatus]         TINYINT            DEFAULT ((0)) NULL,
    [PrintDate]           DATETIME           NULL,
    [ReqShipDate]         DATETIME           NULL,
    [OrderedBy]           [dbo].[pUserID]    NULL,
    [ReceivedBy]          [dbo].[pUserID]    NULL,
    [FOB]                 NVARCHAR (35)      NULL,
    [CurrencyID]          [dbo].[pCurrency]  NOT NULL,
    [ExchRate]            [dbo].[pDec]       DEFAULT ((1)) NULL,
    [ShipToID]            [dbo].[pCustID]    NULL,
    [ShipToAttn]          NVARCHAR (30)      NULL,
    [ShipToName]          NVARCHAR (30)      NULL,
    [ShipToAddr1]         NVARCHAR (30)      NULL,
    [ShipToAddr2]         NVARCHAR (60)      NULL,
    [ShipToCity]          NVARCHAR (30)      NULL,
    [ShipToRegion]        NVARCHAR (10)      NULL,
    [ShipToCountry]       [dbo].[pCountry]   NULL,
    [ShipToPostalCode]    NVARCHAR (10)      NULL,
    [ShipVia]             NVARCHAR (20)      NULL,
    [MemoTaxable]         [dbo].[pDec]       DEFAULT ((0)) NULL,
    [MemoNonTaxable]      [dbo].[pDec]       DEFAULT ((0)) NULL,
    [MemoSalesTax]        [dbo].[pDec]       DEFAULT ((0)) NULL,
    [MemoFreight]         [dbo].[pDec]       DEFAULT ((0)) NULL,
    [MemoMisc]            [dbo].[pDec]       DEFAULT ((0)) NULL,
    [MemoDisc]            [dbo].[pDec]       DEFAULT ((0)) NULL,
    [MemoPrepaid]         [dbo].[pDec]       DEFAULT ((0)) NULL,
    [CheckDate]           DATETIME           NULL,
    [MemoTaxableFgn]      [dbo].[pDec]       DEFAULT ((0)) NULL,
    [MemoNonTaxableFgn]   [dbo].[pDec]       DEFAULT ((0)) NULL,
    [MemoSalesTaxFgn]     [dbo].[pDec]       DEFAULT ((0)) NULL,
    [MemoFreightFgn]      [dbo].[pDec]       DEFAULT ((0)) NULL,
    [MemoMiscFgn]         [dbo].[pDec]       DEFAULT ((0)) NULL,
    [MemoDiscFgn]         [dbo].[pDec]       DEFAULT ((0)) NULL,
    [MemoPrepaidFgn]      [dbo].[pDec]       DEFAULT ((0)) NULL,
    [MemoCheckNo]         [dbo].[pCheckNum]  NULL,
    [MemoDueDate1]        DATETIME           NULL,
    [MemoDueDate2]        DATETIME           NULL,
    [MemoDueDate3]        DATETIME           NULL,
    [MemoPmtAmt1]         [dbo].[pDec]       DEFAULT ((0)) NULL,
    [MemoPmtAmt2]         [dbo].[pDec]       DEFAULT ((0)) NULL,
    [MemoPmtAmt3]         [dbo].[pDec]       DEFAULT ((0)) NULL,
    [MemoPmtAmt1Fgn]      [dbo].[pDec]       DEFAULT ((0)) NULL,
    [MemoPmtAmt2Fgn]      [dbo].[pDec]       DEFAULT ((0)) NULL,
    [MemoPmtAmt3Fgn]      [dbo].[pDec]       DEFAULT ((0)) NULL,
    [MemoTaxClassFreight] TINYINT            DEFAULT ((0)) NULL,
    [MemoTaxClassMisc]    TINYINT            DEFAULT ((0)) NULL,
    [MemoTaxLocID1]       [dbo].[pTaxLoc]    NULL,
    [MemoTaxAmt1]         [dbo].[pDec]       DEFAULT ((0)) NULL,
    [MemoTaxAmt1Fgn]      [dbo].[pDec]       DEFAULT ((0)) NULL,
    [MemoTaxLocID2]       [dbo].[pTaxLoc]    NULL,
    [MemoTaxAmt2]         [dbo].[pDec]       DEFAULT ((0)) NULL,
    [MemoTaxAmt2Fgn]      [dbo].[pDec]       DEFAULT ((0)) NULL,
    [MemoTaxLocID3]       [dbo].[pTaxLoc]    NULL,
    [MemoTaxAmt3]         [dbo].[pDec]       DEFAULT ((0)) NULL,
    [MemoTaxAmt3Fgn]      [dbo].[pDec]       DEFAULT ((0)) NULL,
    [MemoTaxLocID4]       [dbo].[pTaxLoc]    NULL,
    [MemoTaxAmt4]         [dbo].[pDec]       DEFAULT ((0)) NULL,
    [MemoTaxAmt4Fgn]      [dbo].[pDec]       DEFAULT ((0)) NULL,
    [MemoTaxLocID5]       [dbo].[pTaxLoc]    NULL,
    [MemoTaxAmt5]         [dbo].[pDec]       DEFAULT ((0)) NULL,
    [MemoTaxAmt5Fgn]      [dbo].[pDec]       DEFAULT ((0)) NULL,
    [DropShipYn]          BIT                DEFAULT ((0)) NULL,
    [HdrRef]              INT                NULL,
    [BudgetPeriod]        SMALLINT           NULL,
    [BudgetYear]          SMALLINT           NULL,
    [RouteId]             NVARCHAR (10)      NULL,
    [RequestComments]     TEXT               NULL,
    [CF]                  XML                NULL,
    [ExpReceiptDate]      DATETIME           NULL,
    CONSTRAINT [PK_tblPoHistRequestHeader] PRIMARY KEY CLUSTERED ([PostRun] ASC, [TransId] ASC)
);


GO
EXECUTE sp_addextendedproperty @name = N'Version', @value = '11.0.19137.3213', @level0type = N'SCHEMA', @level0name = N'dbo', @level1type = N'TABLE', @level1name = N'tblPoHistRequestHeader';


GO
EXECUTE sp_addextendedproperty @name = N'Comment', @value = 'Build 19137', @level0type = N'SCHEMA', @level0name = N'dbo', @level1type = N'TABLE', @level1name = N'tblPoHistRequestHeader';

