CREATE TABLE [dbo].[tblPoHistInvoiceTot] (
    [PostRun]             [dbo].[pPostRun]    NOT NULL,
    [TransId]             [dbo].[pTransID]    NOT NULL,
    [InvcNum]             [dbo].[pInvoiceNum] NOT NULL,
    [Status]              TINYINT             NULL,
    [InvcDate]            DATETIME            NULL,
    [GLPeriod]            SMALLINT            NULL,
    [FiscalYear]          SMALLINT            NULL,
    [Ten99InvoiceYN]      BIT                 NULL,
    [CurrTaxable]         [dbo].[pDec]        NULL,
    [CurrNonTaxable]      [dbo].[pDec]        NULL,
    [CurrSalesTax]        [dbo].[pDec]        NULL,
    [CurrFreight]         [dbo].[pDec]        NULL,
    [CurrMisc]            [dbo].[pDec]        NULL,
    [CurrDisc]            [dbo].[pDec]        NULL,
    [CurrPrepaid]         [dbo].[pDec]        NULL,
    [CurrTaxableFgn]      [dbo].[pDec]        NULL,
    [CurrNonTaxableFgn]   [dbo].[pDec]        NULL,
    [CurrSalesTaxFgn]     [dbo].[pDec]        NULL,
    [CurrFreightFgn]      [dbo].[pDec]        NULL,
    [CurrMiscFgn]         [dbo].[pDec]        NULL,
    [CurrDiscFgn]         [dbo].[pDec]        NULL,
    [CurrPrepaidFgn]      [dbo].[pDec]        NULL,
    [PostTaxable]         [dbo].[pDec]        NULL,
    [PostNonTaxable]      [dbo].[pDec]        NULL,
    [PostSalesTax]        [dbo].[pDec]        NULL,
    [PostFreight]         [dbo].[pDec]        NULL,
    [PostMisc]            [dbo].[pDec]        NULL,
    [PostDisc]            [dbo].[pDec]        NULL,
    [PostPrepaid]         [dbo].[pDec]        NULL,
    [PostTaxableFgn]      [dbo].[pDec]        NULL,
    [PostNonTaxableFgn]   [dbo].[pDec]        NULL,
    [PostSalesTaxFgn]     [dbo].[pDec]        NULL,
    [PostFreightFgn]      [dbo].[pDec]        NULL,
    [PostMiscFgn]         [dbo].[pDec]        NULL,
    [PostDiscFgn]         [dbo].[pDec]        NULL,
    [PostPrepaidFgn]      [dbo].[pDec]        NULL,
    [CurrCheckNo]         [dbo].[pCheckNum]   NULL,
    [CurrCheckDate]       DATETIME            NULL,
    [CurrBankID]          [dbo].[pBankID]     NULL,
    [CurrChkGlPeriod]     SMALLINT            NULL,
    [CurrChkFiscalYear]   SMALLINT            NULL,
    [CurrDueDate1]        DATETIME            NULL,
    [CurrDueDate2]        DATETIME            NULL,
    [CurrDueDate3]        DATETIME            NULL,
    [CurrPmtAmt1]         [dbo].[pDec]        NULL,
    [CurrPmtAmt2]         [dbo].[pDec]        NULL,
    [CurrPmtAmt3]         [dbo].[pDec]        NULL,
    [CurrPmtAmt1Fgn]      [dbo].[pDec]        NULL,
    [CurrPmtAmt2Fgn]      [dbo].[pDec]        NULL,
    [CurrPmtAmt3Fgn]      [dbo].[pDec]        NULL,
    [CurrTaxClassFreight] TINYINT             NULL,
    [CurrTaxClassMisc]    TINYINT             NULL,
    [CurrTaxAdjClass]     TINYINT             NULL,
    [CurrTaxAdjLocID]     [dbo].[pTaxLoc]     NULL,
    [CurrTaxAdjAmt]       [dbo].[pDec]        NULL,
    [CurrTaxAdjAmtFgn]    [dbo].[pDec]        NULL,
    [InvoiceExchRate]     [dbo].[pDec]        NOT NULL,
    [PmtCurrencyId]       [dbo].[pCurrency]   NULL,
    [PmtExchRate]         [dbo].[pDec]        NOT NULL,
    [GainLoss]            [dbo].[pDec]        NULL,
    [DiscDueDate]         DATETIME            NULL,
    [CF]                  XML                 NULL,
    CONSTRAINT [PK_tblPoHistInvoiceTot] PRIMARY KEY CLUSTERED ([PostRun] ASC, [TransId] ASC, [InvcNum] ASC)
);


GO
EXECUTE sp_addextendedproperty @name = N'Version', @value = '11.0.19137.3213', @level0type = N'SCHEMA', @level0name = N'dbo', @level1type = N'TABLE', @level1name = N'tblPoHistInvoiceTot';


GO
EXECUTE sp_addextendedproperty @name = N'Comment', @value = 'Build 19137', @level0type = N'SCHEMA', @level0name = N'dbo', @level1type = N'TABLE', @level1name = N'tblPoHistInvoiceTot';

