CREATE TABLE [dbo].[tblPoHistHeader] (
    [PostRun]             [dbo].[pPostRun]   NOT NULL,
    [TransId]             [dbo].[pTransID]   NOT NULL,
    [BatchId]             [dbo].[pBatchID]   NOT NULL,
    [TransType]           SMALLINT           NULL,
    [LocId]               [dbo].[pLocID]     NULL,
    [VendorId]            [dbo].[pVendorID]  NOT NULL,
    [Notes]               TEXT               NULL,
    [DistCode]            [dbo].[pDistCode]  NOT NULL,
    [TermsCode]           [dbo].[pTermsCode] NOT NULL,
    [TransDate]           DATETIME           NULL,
    [TaxGrpID]            [dbo].[pTaxLoc]    NOT NULL,
    [TaxableYn]           BIT                NULL,
    [PrintStatus]         TINYINT            NULL,
    [PrintDate]           DATETIME           NULL,
    [ReqShipDate]         DATETIME           NULL,
    [OrderedBy]           [dbo].[pUserID]    NULL,
    [ReceivedBy]          [dbo].[pUserID]    NULL,
    [FOB]                 VARCHAR (35)       NULL,
    [CurrencyID]          [dbo].[pCurrency]  NOT NULL,
    [ExchRate]            [dbo].[pDec]       NULL,
    [ShipToID]            [dbo].[pCustID]    NULL,
    [ShipToAttn]          VARCHAR (30)       NULL,
    [ShipToName]          VARCHAR (30)       NULL,
    [ShipToAddr1]         VARCHAR (30)       NULL,
    [ShipToAddr2]         VARCHAR (60)       NULL,
    [ShipToCity]          VARCHAR (30)       NULL,
    [ShipToRegion]        VARCHAR (10)       NULL,
    [ShipToCountry]       [dbo].[pCountry]   NULL,
    [ShipToPostalCode]    VARCHAR (10)       NULL,
    [ShipVia]             VARCHAR (20)       NULL,
    [MemoTaxable]         [dbo].[pDec]       NULL,
    [MemoNonTaxable]      [dbo].[pDec]       NULL,
    [MemoSalesTax]        [dbo].[pDec]       NULL,
    [MemoFreight]         [dbo].[pDec]       NULL,
    [MemoMisc]            [dbo].[pDec]       NULL,
    [MemoDisc]            [dbo].[pDec]       NULL,
    [MemoPrepaid]         [dbo].[pDec]       NULL,
    [CheckDate]           DATETIME           NULL,
    [MemoTaxableFgn]      [dbo].[pDec]       NULL,
    [MemoNonTaxableFgn]   [dbo].[pDec]       NULL,
    [MemoSalesTaxFgn]     [dbo].[pDec]       NULL,
    [MemoFreightFgn]      [dbo].[pDec]       NULL,
    [MemoMiscFgn]         [dbo].[pDec]       NULL,
    [MemoDiscFgn]         [dbo].[pDec]       NULL,
    [MemoPrepaidFgn]      [dbo].[pDec]       NULL,
    [MemoCheckNo]         [dbo].[pCheckNum]  NULL,
    [MemoDueDate1]        DATETIME           NULL,
    [MemoDueDate2]        DATETIME           NULL,
    [MemoDueDate3]        DATETIME           NULL,
    [MemoPmtAmt1]         [dbo].[pDec]       NULL,
    [MemoPmtAmt2]         [dbo].[pDec]       NULL,
    [MemoPmtAmt3]         [dbo].[pDec]       NULL,
    [MemoPmtAmt1Fgn]      [dbo].[pDec]       NULL,
    [MemoPmtAmt2Fgn]      [dbo].[pDec]       NULL,
    [MemoPmtAmt3Fgn]      [dbo].[pDec]       NULL,
    [MemoTaxClassFreight] TINYINT            NULL,
    [MemoTaxClassMisc]    TINYINT            NULL,
    [MemoTaxLocID1]       [dbo].[pTaxLoc]    NULL,
    [MemoTaxAmt1]         [dbo].[pDec]       NULL,
    [MemoTaxAmt1Fgn]      [dbo].[pDec]       NULL,
    [MemoTaxLocID2]       [dbo].[pTaxLoc]    NULL,
    [MemoTaxAmt2]         [dbo].[pDec]       NULL,
    [MemoTaxAmt2Fgn]      [dbo].[pDec]       NULL,
    [MemoTaxLocID3]       [dbo].[pTaxLoc]    NULL,
    [MemoTaxAmt3]         [dbo].[pDec]       NULL,
    [MemoTaxAmt3Fgn]      [dbo].[pDec]       NULL,
    [MemoTaxLocID4]       [dbo].[pTaxLoc]    NULL,
    [MemoTaxAmt4]         [dbo].[pDec]       NULL,
    [MemoTaxAmt4Fgn]      [dbo].[pDec]       NULL,
    [MemoTaxLocID5]       [dbo].[pTaxLoc]    NULL,
    [MemoTaxAmt5]         [dbo].[pDec]       NULL,
    [MemoTaxAmt5Fgn]      [dbo].[pDec]       NULL,
    [HdrRef]              INT                NOT NULL,
    [DropShipYn]          BIT                DEFAULT ((0)) NOT NULL,
    [CF]                  XML                NULL,
    [GroupId]             [dbo].[pTransID]   NULL,
    [RequestedDate]       DATETIME           NULL,
    [RequestedBy]         [dbo].[pUserID]    NULL,
    [ApprovedDate]        DATETIME           NULL,
    [ApprovedBy]          [dbo].[pUserID]    NULL,
    [RequestStatus]       TINYINT            NULL,
    [ExpReceiptDate]      DATETIME           NULL,
    CONSTRAINT [PK_tblPoHistHeader] PRIMARY KEY CLUSTERED ([PostRun] ASC, [TransId] ASC)
);


GO
EXECUTE sp_addextendedproperty @name = N'Version', @value = '11.0.19137.3213', @level0type = N'SCHEMA', @level0name = N'dbo', @level1type = N'TABLE', @level1name = N'tblPoHistHeader';


GO
EXECUTE sp_addextendedproperty @name = N'Comment', @value = 'Build 19137', @level0type = N'SCHEMA', @level0name = N'dbo', @level1type = N'TABLE', @level1name = N'tblPoHistHeader';

