CREATE TABLE [dbo].[tblPaW2] (
    [Counter]        INT            IDENTITY (1, 1) NOT NULL,
    [EmployeeId]     [dbo].[pEmpID] NOT NULL,
    [BoxA]           NVARCHAR (255) NULL,
    [BoxB]           NVARCHAR (17)  NULL,
    [BoxC]           NVARCHAR (50)  NULL,
    [BoxC1]          NVARCHAR (70)  NULL,
    [BoxC2]          NVARCHAR (50)  NULL,
    [BoxD]           INT            CONSTRAINT [DF_tblPaW2_BoxD] DEFAULT ((0)) NOT NULL,
    [BoxE]           NVARCHAR (70)  NULL,
    [BoxE1]          NVARCHAR (70)  NULL,
    [BoxF]           NVARCHAR (100) NULL,
    [BoxF1]          NVARCHAR (25)  NULL,
    [BoxF2]          NVARCHAR (2)   NULL,
    [BoxF3]          NVARCHAR (10)  NULL,
    [BoxF4]          NVARCHAR (20)  NULL,
    [Box1]           [dbo].[pDec]   CONSTRAINT [DF_tblPaW2_Box1] DEFAULT ((0)) NOT NULL,
    [Box2]           [dbo].[pDec]   CONSTRAINT [DF_tblPaW2_Box2] DEFAULT ((0)) NOT NULL,
    [Box3]           [dbo].[pDec]   CONSTRAINT [DF_tblPaW2_Box3] DEFAULT ((0)) NOT NULL,
    [Box4]           [dbo].[pDec]   CONSTRAINT [DF_tblPaW2_Box4] DEFAULT ((0)) NOT NULL,
    [Box5]           [dbo].[pDec]   CONSTRAINT [DF_tblPaW2_Box5] DEFAULT ((0)) NOT NULL,
    [Box6]           [dbo].[pDec]   CONSTRAINT [DF_tblPaW2_Box6] DEFAULT ((0)) NOT NULL,
    [Box7]           [dbo].[pDec]   CONSTRAINT [DF_tblPaW2_Box7] DEFAULT ((0)) NOT NULL,
    [Box8]           [dbo].[pDec]   CONSTRAINT [DF_tblPaW2_Box8] DEFAULT ((0)) NOT NULL,
    [Box9]           [dbo].[pDec]   CONSTRAINT [DF_tblPaW2_Box9] DEFAULT ((0)) NOT NULL,
    [Box10]          [dbo].[pDec]   CONSTRAINT [DF_tblPaW2_Box10] DEFAULT ((0)) NOT NULL,
    [Box11]          [dbo].[pDec]   CONSTRAINT [DF_tblPaW2_Box11] DEFAULT ((0)) NOT NULL,
    [Box12]          [dbo].[pDec]   CONSTRAINT [DF_tblPaW2_Box12] DEFAULT ((0)) NOT NULL,
    [Box13Line1]     [dbo].[pDec]   CONSTRAINT [DF_tblPaW2_Box13Line1] DEFAULT ((0)) NOT NULL,
    [Box13LineDesc1] NVARCHAR (2)   NULL,
    [Box13Line2]     [dbo].[pDec]   CONSTRAINT [DF_tblPaW2_Box13Line2] DEFAULT ((0)) NOT NULL,
    [Box13LineDesc2] NVARCHAR (2)   NULL,
    [Box13Line3]     [dbo].[pDec]   CONSTRAINT [DF_tblPaW2_Box13Line3] DEFAULT ((0)) NOT NULL,
    [Box13LineDesc3] NVARCHAR (2)   NULL,
    [Box13Line4]     [dbo].[pDec]   CONSTRAINT [DF_tblPaW2_Box13Line4] DEFAULT ((0)) NOT NULL,
    [Box13LineDesc4] NVARCHAR (2)   NULL,
    [Box14Line1]     [dbo].[pDec]   CONSTRAINT [DF_tblPaW2_Box14Line1] DEFAULT ((0)) NOT NULL,
    [Box14LineDesc1] NVARCHAR (10)  NULL,
    [Box14Line2]     [dbo].[pDec]   CONSTRAINT [DF_tblPaW2_Box14Line2] DEFAULT ((0)) NOT NULL,
    [Box14LineDesc2] NVARCHAR (10)  NULL,
    [Box14Line3]     [dbo].[pDec]   CONSTRAINT [DF_tblPaW2_Box14Line3] DEFAULT ((0)) NOT NULL,
    [Box14LineDesc3] NVARCHAR (10)  NULL,
    [Box15a]         BIT            CONSTRAINT [DF_tblPaW2_Box15a] DEFAULT ((0)) NOT NULL,
    [Box15b]         BIT            CONSTRAINT [DF_tblPaW2_Box15b] DEFAULT ((0)) NOT NULL,
    [Box15c]         BIT            CONSTRAINT [DF_tblPaW2_Box15c] DEFAULT ((0)) NOT NULL,
    [Box15d]         BIT            CONSTRAINT [DF_tblPaW2_Box15d] DEFAULT ((0)) NOT NULL,
    [Box15E]         BIT            CONSTRAINT [DF_tblPaW2_Box15E] DEFAULT ((0)) NOT NULL,
    [Box15F]         BIT            CONSTRAINT [DF_tblPaW2_Box15F] DEFAULT ((0)) NOT NULL,
    [Box15G]         BIT            CONSTRAINT [DF_tblPaW2_Box15G] DEFAULT ((0)) NOT NULL,
    [Box16A]         NVARCHAR (2)   NULL,
    [Box16b]         NVARCHAR (20)  NULL,
    [Box17]          [dbo].[pDec]   CONSTRAINT [DF_tblPaW2_Box17] DEFAULT ((0)) NOT NULL,
    [Box18]          [dbo].[pDec]   CONSTRAINT [DF_tblPaW2_Box18] DEFAULT ((0)) NOT NULL,
    [Box19]          NVARCHAR (30)  NULL,
    [Box20]          [dbo].[pDec]   CONSTRAINT [DF_tblPaW2_Box20] DEFAULT ((0)) NOT NULL,
    [Box21]          [dbo].[pDec]   CONSTRAINT [DF_tblPaW2_Box21] DEFAULT ((0)) NOT NULL,
    [Box19a]         NVARCHAR (30)  NULL,
    [Box20a]         [dbo].[pDec]   CONSTRAINT [DF_tblPaW2_Box20a] DEFAULT ((0)) NOT NULL,
    [Box21a]         [dbo].[pDec]   CONSTRAINT [DF_tblPaW2_Box21a] DEFAULT ((0)) NOT NULL,
    [AddnlBox13]     BIT            CONSTRAINT [DF_tblPaW2_AddnlBox13] DEFAULT ((0)) NOT NULL,
    [AddnlBox14]     BIT            CONSTRAINT [DF_tblPaW2_AddnlBox14] DEFAULT ((0)) NOT NULL,
    [FirstLine]      BIT            CONSTRAINT [DF_tblPaW2_FirstLine] DEFAULT ((0)) NOT NULL,
    [NJFLIAmt]       [dbo].[pDec]   NULL,
    CONSTRAINT [PK_tblPaW2] PRIMARY KEY CLUSTERED ([Counter] ASC)
);


GO
EXECUTE sp_addextendedproperty @name = N'Version', @value = '11.0.19137.3213', @level0type = N'SCHEMA', @level0name = N'dbo', @level1type = N'TABLE', @level1name = N'tblPaW2';


GO
EXECUTE sp_addextendedproperty @name = N'Comment', @value = 'Build 19137', @level0type = N'SCHEMA', @level0name = N'dbo', @level1type = N'TABLE', @level1name = N'tblPaW2';

