CREATE TABLE [dbo].[xxxtblJmTech] (
    [TechId]                  INT           IDENTITY (1, 1) NOT NULL,
    [Tech]                    VARCHAR (3)   NULL,
    [Name]                    VARCHAR (255) NULL,
    [Addr1]                   VARCHAR (255) NULL,
    [Addr2]                   VARCHAR (255) NULL,
    [City]                    VARCHAR (255) NULL,
    [Region]                  VARCHAR (255) NULL,
    [Country]                 VARCHAR (255) NULL,
    [PostalCode]              VARCHAR (10)  NULL,
    [IntlPrefix]              VARCHAR (6)   NULL,
    [Phone]                   VARCHAR (15)  NULL,
    [Fax]                     VARCHAR (15)  NULL,
    [Pager]                   VARCHAR (15)  NULL,
    [Mobile]                  VARCHAR (15)  NULL,
    [Email]                   TEXT          NULL,
    [EmplId]                  VARCHAR (10)  NULL,
    [InactiveYN]              BIT           CONSTRAINT [DF_tblJmTech2_InactiveYN] DEFAULT ((0)) NULL,
    [BranchId]                INT           NULL,
    [DivisionId]              INT           NULL,
    [DeptId]                  INT           NULL,
    [PayBasedOn]              TINYINT       NULL,
    [DfltLaborCostPerHour]    FLOAT (53)    NULL,
    [DfltLaborCostPerPoint]   FLOAT (53)    NULL,
    [CosOffset]               VARCHAR (40)  NULL,
    [VehicleId]               INT           NULL,
    [GasCard]                 VARCHAR (255) NULL,
    [GasPIN]                  VARCHAR (255) NULL,
    [DfltSvcJobYN]            BIT           CONSTRAINT [DF_tblJmTech2_DfltSvcJobYN] DEFAULT ((0)) NULL,
    [ts]                      ROWVERSION    NULL,
    [DfltTaxLocId]            VARCHAR (10)  NULL,
    [ActiveDirectoryUserName] VARCHAR (100) NULL,
    [TechDfltWhseLocID]       VARCHAR (10)  NULL,
    CONSTRAINT [PK_tblJmTech2] PRIMARY KEY CLUSTERED ([TechId] ASC) WITH (FILLFACTOR = 80)
);

