
CREATE PROCEDURE dbo.trav_DSViewRebuildAll_proc
AS
SET NOCOUNT ON
BEGIN TRY

	Declare @curEntity cursor
	Declare @EntityName nvarchar(255)
	
	Set @curEntity = Cursor for 
		Select EntityName From dbo.tblSmCustomFieldEntity Group by EntityName
		For Read Only
		
	Open @curEntity
	If @@CURSOR_ROWS <> 0
	Begin
		Fetch Next From @curEntity Into @EntityName
		While (@@FETCH_STATUS = 0)
		Begin
			Exec dbo.trav_DSViewBuilder_proc @EntityName
			Fetch Next From @curEntity Into @EntityName
		End
		Close @curEntity
	End
	Deallocate @curEntity

	--return any errors generated by the execution
	Return @@Error
END TRY
BEGIN CATCH
	EXEC dbo.trav_RaiseError_proc
END CATCH
GO
EXECUTE sp_addextendedproperty @name = N'Version', @value = '11.0.19137.3213', @level0type = N'SCHEMA', @level0name = N'dbo', @level1type = N'PROCEDURE', @level1name = N'trav_DSViewRebuildAll_proc';


GO
EXECUTE sp_addextendedproperty @name = N'Comment', @value = 'Build 19137', @level0type = N'SCHEMA', @level0name = N'dbo', @level1type = N'PROCEDURE', @level1name = N'trav_DSViewRebuildAll_proc';

