CREATE VIEW [dbo].[trav_tblApCheckHist_view]
AS
SELECT t.[BankAccountType]
, t.[BankAcctNum]
, t.[BankId]
, t.[BaseGrossAmtDue]
, t.[CheckDate]
, t.[CheckNum]
, t.[CheckRun]
, t.[Counter]
, t.[CurrencyID]
, t.[DeliveryType]
, t.[DiscAmt]
, t.[DiscAmtCalc]
, t.[DiscAmtFgn]
, t.[DiscDueDate]
, t.[DiscLost]
, t.[DiscLostFgn]
, t.[DiscTaken]
, t.[DiscTakenFgn]
, t.[DistCode]
, t.[ExchRate]
, t.[FiscalYear]
, t.[GLAcctAP]
, t.[GLAcctGainLoss]
, t.[GLCashAcct]
, t.[GLDiscAcct]
, t.[GlPeriod]
, t.[GrossAmtDue]
, t.[GrossAmtDueFgn]
, t.[InvoiceDate]
, t.[InvoiceNum]
, t.[NetDueDate]
, t.[NetPaidCalc]
, t.[PayToAddr1]
, t.[PayToAddr2]
, t.[PayToAttn]
, t.[PayToCity]
, t.[PayToCountry]
, t.[PayToName]
, t.[PayToPostalCode]
, t.[PayToRegion]
, t.[PmtCurrencyID]
, t.[PmtExchRate]
, t.[PmtType]
, t.[PostRun]
, t.[RoutingCode]
, t.[SelectedYn]
, t.[SumHistPeriod]
, t.[Ten99FormCode]
, t.[Ten99InvoiceYN]
, t.[TermsCode]
, t.[VendorID]
, t.[VoidBankId]
, t.[VoidDate]
, t.[VoidYn]
 FROM dbo.[tblApCheckHist] t
GO
EXECUTE sp_addextendedproperty @name = N'Version', @value = '11.0.19137.3213', @level0type = N'SCHEMA', @level0name = N'dbo', @level1type = N'VIEW', @level1name = N'trav_tblApCheckHist_view';


GO
EXECUTE sp_addextendedproperty @name = N'Comment', @value = 'Build 19137', @level0type = N'SCHEMA', @level0name = N'dbo', @level1type = N'VIEW', @level1name = N'trav_tblApCheckHist_view';

