CREATE VIEW [dbo].[trav_tblArHistHeader_View]
AS
SELECT t.[BatchId]
, t.[BillingFormat]
, t.[BillingPeriodFrom]
, t.[BillingPeriodThru]
, t.[BlanketRef]
, t.[CalcGainLoss]
, t.[CredMemNum]
, t.[CurrencyID]
, t.[CustId]
, t.[CustLevel]
, t.[CustPONum]
, t.[DiscAmt]
, t.[DiscAmtFgn]
, t.[DiscDueDate]
, t.[DistCode]
, t.[ExchRate]
, t.[FiscalYear]
, t.[Freight]
, t.[FreightFgn]
, t.[GLAcctFreight]
, t.[GlAcctGainLoss]
, t.[GLAcctMisc]
, t.[GLAcctReceivables]
, t.[GLAcctSalesTax]
, t.[GLPeriod]
, t.[InvcDate]
, t.[InvcNum]
, t.[Misc]
, t.[MiscFgn]
, t.[NetDueDate]
, t.[NonTaxSubtotal]
, t.[NonTaxSubtotalFgn]
, t.[Notes]
, t.[OrderDate]
, t.[PackNum]
, t.[PickNum]
, t.[PMTransType]
, t.[PODate]
, t.[PostDate]
, t.[PostRun]
, t.[PrintOption]
, t.[PrintStatus]
, t.[ProjItem]
, t.[Rep1CommRate]
, t.[Rep1Id]
, t.[Rep1Pct]
, t.[Rep2CommRate]
, t.[Rep2Id]
, t.[Rep2Pct]
, t.[ReqShipDate]
, t.[ReturnDirectToStockYn]
, t.[SalesTax]
, t.[SalesTaxFgn]
, t.[ShipDate]
, t.[ShipNum]
, t.[ShipToAddr1]
, t.[ShipToAddr2]
, t.[ShipToCity]
, t.[ShipToCountry]
, t.[ShipToID]
, t.[ShipToName]
, t.[ShipToPhone]
, t.[ShipToPostalCode]
, t.[ShipToRegion]
, t.[ShipVia]
, t.[SoldToId]
, t.[Source]
, t.[SourceId]
, t.[SourceInfo]
, t.[SumHistPeriod]
, t.[TaxableYN]
, t.[TaxAdj]
, t.[TaxAmtAdj]
, t.[TaxAmtAdjFgn]
, t.[TaxClassAdj]
, t.[TaxClassFreight]
, t.[TaxClassMisc]
, t.[TaxGrpID]
, t.[TaxLocAdj]
, t.[TaxOnFreight]
, t.[TaxSubtotal]
, t.[TaxSubtotalFgn]
, t.[TermsCode]
, t.[TotCost]
, t.[TotCostFgn]
, t.[TotPmtAmt]
, t.[TotPmtAmtFgn]
, t.[TotPmtGainLoss]
, t.[TransId]
, t.[TransType]
, t.[VoidYn]
, t.[WhseId]
, e.[cf_Invoice Comments]
 FROM dbo.[tblArHistHeader] t
 LEFT JOIN
 ( SELECT pvt.[PostRun]
	, pvt.[TransId]
	, Cast(pvt.[Invoice Comments] As nvarchar(max)) AS [cf_Invoice Comments]
	 FROM
		 ( SELECT t.[PostRun], t.[TransId], [Name], [Value]
		 FROM
			 ( SELECT t.[PostRun], t.[TransId]
			 , e.props.value('./Name[1]', 'NVARCHAR(max)') as [Name]
			 , e.props.value('./Value[1]', 'NVARCHAR(max)') as [Value]
			 FROM dbo.[tblArHistHeader] t
			 CROSS APPLY t.CF.nodes('/ArrayOfEntityPropertyOfString/EntityPropertyOfString') as e(props)
			 WHERE (e.props.exist('Name') = 1) AND (e.props.exist('Value') = 1)
		 ) t
	 ) tmp
	 PIVOT (Max([Value]) FOR [Name] IN ([Invoice Comments])) AS pvt
) e on  t.[PostRun] = e.[PostRun] AND t.[TransId] = e.[TransId]